### ISSUE TITLE
Doesn't work with FanControl V153 anymore

### ISSUE THREAD

**Issue by lutzgooren** [vision57/FanControl.GPU-Z#2]
As the title suggests, it was fine with V152 and older, but it won't work with V153 anymore.

**Comment by vision57** [comment]
I will confirm this soon.

**Comment by lutzgooren** [comment]
Thanks for answering :) - It seems that it was a small hiccup. I've rolled back to V152 and it was working again, so I've updated to V153 a second time, deactivated the InpOut in sensor settings reopened it and now it seems to be working fine. I was also able to re-enable InpOut afterwards.
