### ISSUE TITLE
[Added] Add GPU-Z to ReadMe

### ISSUE THREAD

**Issue by Rexadev** [vision57/FanControl.GPU-Z#3]

**Comment by Rem0o** [comment]
Is GPU-Z Running?

**Comment by Rexadev** [comment]
Working, you should add that to the readme

@Rem0o

**Comment by Rem0o** [comment]
![image](https://github.com/vision57/FanControl.GPU-Z/assets/14118956/bf587270-7266-4f56-8b84-c4e1bd1304be)

**Comment by Rexadev** [comment]
Add link to download gpuz @Rem0o

**Comment by Rem0o** [comment]
You are kinda doing things in reverse order.  You should be using this plugin if you are already using GPU-Z.  By the way this is not my repo.   You can always create a PR for the readme if you see fit.

**Comment by vision57** [comment]
gpu-z link added to readme.
